name: DHL Report Automation

on:
  schedule:
    # Run at 8 AM Vietnam time (1 AM UTC)
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  automate-dhl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account file
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > service-account.json
    
    - name: Run DHL automation
      env:
        DHL_USERNAME: ${{ secrets.DHL_USERNAME }}
        DHL_PASSWORD: ${{ secrets.DHL_PASSWORD }}
      run: python dhl_automation.py
