name: DHL Report Automation

on:
  schedule:
    - cron: '0 1 * * *'  # 8:00 AM Vietnam time (UTC+7)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Selenium with Chrome
        uses: nanasess/setup-chromedriver@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account file
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run automation script
        run: |
          # Start ChromeDriver
          chromedriver --port=4444 &
          sleep 3  # Give ChromeDriver time to start
          
          # Run the script
          python dhl_report_automation.py
        env:
          DHL_USERNAME: ${{ secrets.DHL_USERNAME }}
          DHL_PASSWORD: ${{ secrets.DHL_PASSWORD }}
