name: DHL Report Automation

on:
  schedule:
    - cron: '0 1 * * *'  # 8:00 AM Vietnam time (UTC+7)
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          driver-version: stable

      - name: Check Chrome and ChromeDriver versions
        run: |
          chrome --version
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account file
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run automation script
        run: python dhl_report_automation.py
        env:
          DHL_USERNAME: ${{ secrets.DHL_USERNAME }}
          DHL_PASSWORD: ${{ secrets.DHL_PASSWORD }}
