name: DHL Report Automation

on:
  schedule:
    - cron: '0 1 * * *'  # 8:00 AM Vietnam time (UTC+7)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '132.0.6834.159'  # Match the version with installed Chrome

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account file
        run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run automation script
        run: python dhl_report_automation.py
        env:
          DHL_USERNAME: ${{ secrets.DHL_USERNAME }}
          DHL_PASSWORD: ${{ secrets.DHL_PASSWORD }}
          PYTHONUNBUFFERED: 1  # This ensures Python prints output immediately
