name: DHL Report Automation

on:
  schedule:
    # Run at 8 AM Vietnam time (1 AM UTC)
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  automate-dhl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create service account file
      run: |
        echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT }}" > service-account.json
    
    - name: Run DHL automation
      env:
        DHL_USERNAME: ${{ secrets.DHL_USERNAME }}
        DHL_PASSWORD: ${{ secrets.DHL_PASSWORD }}
      run: python dhl_automation.py
